version: '3.2'

services:
    redis:
        image: "redis:alpine"
        command: redis-server
        ports:
            - "6379:6379"

        volumes:
            - $PWD/redis/redis-data:/var/lib/redis
            - $PWD/redis/redis.config:/usr/local/etc/redis/redis.config

        environment:
            - REDIS_REPLICATION_MODE=master

        networks:
            - bull-redis

networks:
    bull-redis:
